### ISSUE TITLE
Monitoring? (HTTPS currently down!)

### ISSUE THREAD

**Issue by elf-pavlik** [perma-id/w3id.org#87] opened 2015-05-13 07:56 UTC
Do you have some kind of remote monitoring in place?

HTTPS seems down at this moment, trying from local and remote machine:

```shell
curl https://w3id.org -I
curl: (7) Failed to connect to w3id.org port 443: No route to host
```

also [JSON-LD Playgrounds](http://json-ld.org/playground/) says: **Error loading context URL: https://w3id.org/plp/v1**

HTTP works though

```shell
curl http://w3id.org -I 
HTTP/1.1 200 OK
Server: BaseHTTP/0.3 Python/2.6.6
Content-type: text/html
Date: Wed, 13 May 2015 07:56:06 GMT
Age: 0
Via: 1.1 varnish
Connection: close
```

**Comment by phillord** [comment] 2015-05-13 10:38
Down here also.

**Comment by msporny** [comment] 2015-05-13 13:51
Duplicate of #81, closing.

**Closed by msporny** 2015-05-13 13:51 UTC

**Comment by msporny** [comment] 2015-05-13 13:53
> Do you have some kind of remote monitoring in place?

yes we do, but that doesn't help when it's 3am here and the alarms start going off :P

Our remote monitoring only checks http, so we need to fix that... working on fixing it now.

**Comment by msporny** [comment] 2015-05-13 14:12
Remote monitoring for https is now setup and working.

**Comment by elf-pavlik** [comment] 2015-05-13 14:21
:+1: thanks for all the recent upgrades to w3id.org!

**Comment by prototypo** [comment] 2015-05-13 14:54
+1. Thanks, Manu and David!

Regards,
Dave
--
http://about.me/david_wood
